### ISSUE TITLE
Add support for the /dev/swradioX device?

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dabtools#7] opened 2017-01-31 19:46 UTC
In some situations, e.g. Debian Sid, but not it seems Fedora Rawhide, plugging in a SDR USB device causes the rtl2832_sdr device driver to start and thus create the file /dev/swradio0. I assume that this device will use something closely akin to the standard Video4Linux API for DVB. If so then it should be possible to write a version of dab4eti that works with this device rather than using librtlsdr.

If this route is progressed might it be worth writing the code in C++11 (or even C++14) rather than C?

**Comment by mpbraendli** [comment] 2017-02-01 07:14
What would be the goal of such a change? If the aim is to improve the reception quality of dabtools then it would be better to focus on the DSP happening inside dab2eti.
Is there something `/dev/swradio0` is able to do that librtlsdr isn't? Is this stable or is it going to give us maintenance headaches?
About the choice of the language: we ought to agree on what platforms we want to support for dabtools and dablin. For the transmit-side tools the platform I commit to supporting is debian stable. This makes using C++14 difficult.

**Comment by russel** [comment] 2017-02-03 06:46
The librtlsdr and rtl2832_sdr camps appear two distinct ones with no accommodation (OsMoCom explicitly deny any association with Antti Palosaari), yet they provide the same facility. This seems to echo a similar divide between the radio community and the video community. I am coming at this from the Linux DVB end of things and so have a mindset more associated with Linux device drivers and layers of software above them. The history of DVB stick use in SDR revolves around direct control without kernel intervention – better for portability across Linux, MacOS, Windows, but is this an issue? The librtlsdr way of doing things is exactly what the kernel drivers do, so just two ways of doing the same thing. Should dab2eti be abstracting over this lower level to allow both?

I am investigating SDR-J to see if there are ways of improving the dab2eti code – assuming I can ever get SDR-J to build.

The rtl2832_sdr driver seems fairly stable, but this may just be that no-one is using it, and so there are no bug reports, and hence no fixes.

Sadlly it seems librtlsdr is not evolving despite lots of use, lots of bug reports.

dab2eti is currently C code I'm not sure if it is C11 compliant though. I can see arguments for continuing with C11 (cased on dependencies) and for switching to C++11, though the latter has the downside of needing effort. On the other hand a C → C++11 transform would likely lead to review of the algorithms and thus to the better handling of DSP.

**Comment by mpbraendli** [comment] 2017-02-11 11:15
What's the decision on this question?
(As you can see, I don't like seeing open issues staying in an unclear state :-D )

**Comment by russel** [comment] 2017-02-11 12:08
:-)

Given the tenor of our other conversation, if we go with a Rust rewrite then I will subsume this work into that work, it seems like the right and natural thing to do. So for me the answer to the question is "Yes." all that remains is the vector for achieving the goal.

**Comment by mpbraendli** [comment] 2017-11-15 05:44
This is somewhat a duplicate of issue https://github.com/Opendigitalradio/dabtools/issues/10

**Closed as completed by mpbraendli** 2017-11-15 05:44 UTC
Labels: question
