### ISSUE TITLE
New branch elgroj_tuningstability

### ISSUE THREAD

**Issue by mpbraendli** [Opendigitalradio/dabtools#14] opened 2017-07-07 10:36 UTC
I've merged elgroj/tuningStability into our master branch, and created the branch elgroj_tuningstability. I observe faster locking with my receiver using that branch.
Are you ok if I push those changes into "master"?
Cheers
mpb

**Comment by basicmaster** [comment] 2017-07-08 10:10
One thing I notice is that `dab2eti` now takes three times the CPU load as before...

**Comment by andimik** [comment] 2017-07-09 07:35
This is a No-Go for me. Thanks for finding that out.

**Comment by basicmaster** [comment] 2017-07-09 07:57
I haven't yet checked where this comes from, but this could possibly be fixed so that we can benefit from the other improvements.

**Comment by mpbraendli** [comment] 2017-07-09 08:43
I'm glad I asked first :-)
I wonder if this comes from the viterbi decoder (spiral viterbi versus ka9q), or from other parts.
If I find the time, I will compare the performance using gprof or valgrind's callgrind.

**Comment by mpbraendli** [comment] 2017-07-14 07:08
I do see an increase in CPU usage of around 2x. I wanted to compare with and without spiral viterbi enabled, but I'm not able to compile it on "master", whereas on elgroj_tuningstability it works.

    cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_SPIRAL_VITERBI=On
    make
    [...]
    CMakeFiles/dab2eti.dir/viterbi_spiral.c.o: In function `update_viterbi_blk_GENERIC':
    /[...]/dabtools/src/viterbi_spiral.c:312: undefined reference to `renormalize'

Are you able to compile master with spiral viterbi?

**Comment by russel** [comment] 2017-11-13 14:56
@mpbraendli Apologies for not responding to this for so long. I'll check things out and report back.

**Comment by russel** [comment] 2017-11-13 15:41
The issue is -DCMAKE_BUILD_TYPE=Debug master builds fine in release mode.

I am guessing that renormalize is marked as inline without being static is the problem?

Yes it is, I will send in a pull request against master.

Pull request #15 should deal with this.

**Closed as completed** 2018-04-05 08:32 UTC
Labels: enhancement, question
